# -*- coding: utf-8 -*-

# LEFT_ARROW = '←'       # LEFTWARDS ARROW 8592
# RIGHT_ARROW = '→'      # RIGHTWARDS ARROW 8594
# LEFT_RIGHT_ARROW '↔'   # LEFT RIGHT ARROW 8596

LEFT_ARROW = '⟵'       # LONG LEFTWARDS ARROW 10229
RIGHT_ARROW = '⟶'      # LONG RIGHTWARDS ARROW 10230
LEFT_RIGHT_ARROW = '⟷' # LONG LEFT RIGHT ARROW 10231

# LEFT_ARROW = '⇦'       # LEFTWARDS WHITE ARROW 8678
# RIGHT_ARROW = '⇨'      # RIGHTWARDS WHITE ARROW 8680
# LEFT_RIGHT_ARROW = '⬄' # LEFT RIGHT WHITE ARROW 11012

# LEFT_ARROW = '🡐'       # LEFTWARDS SANS-SERIF ARROW 129104
# RIGHT_ARROW = '🡒'      # RIGHTWARDS SANS-SERIF ARROW 129106
# LEFT_RIGHT_ARROW = '🡘' # LEFT RIGHT SANS-SERIF ARROW 129112

# LEFT_ARROW = '⭠'       # LEFTWARDS TRIANGLE-HEADED ARROW 11104
# RIGHT_ARROW = '⭢'      # RIGHTWARDS TRIANGLE-HEADED ARROW 11106
# LEFT_RIGHT_ARROW = '⭤' # LEFT RIGHT TRIANGLE-HEADED ARROW 11108
